#!/usr/bin/python3.5

# Use Try statements to handle Errors.

# Method I: use if 
''' Use if and while statements'''
while True:
	reply = input( "1. Input a number>> ")
	if reply == "stop":
		break;
	elif not reply.isdigit():
		print( "Error!!" )
	else:
		print( int( reply ) **2 )
print( "Bye!" )

# Method II: Use Try, Except, Else Statements
while True:
	reply = input( "2. Enter>> " )
	if reply == "stop":
		break;
	try:
		num = int( reply )
	except: # if try statement runs into error
		print( "Error!" )
	else: # else is the same feild with try
		print( num ** 2 )
print( "Bye!" )

	
# Method III: No else 
while True:
	reply = input( "3. Enter>> " )
	if reply == "stop":
		break;
	try:
		print( int( reply )**2 )
	except: # if try statement runs into error
		print( "Error!" )
print( "Bye!" )
	
