#!/usr/bin/python3

# Instances for COMPREHESIONS, for list

Matrix = [ [ 2, 2, 3],
		   [ 100, 200, 300],
		   [ 200, 300, 400] ]
 
# Method 1
col1 = [ row[0] for row in Matrix ]
print( col1 )

#Method 2 
col1 = [ ] 
for row in Matrix:
	col1.append( row[0] )
print( col1 )

# Use comprehension with filter
Filter = [ X*2 for X in range( -10, 21, 3) if X%2 == 0 ]
print( Filter )


# COMPREHENSIONS for dict

dic4 = { key: val for ( key, val) in zip( ['a','b','c'], [1,2,3] ) }
print( "The dic4 is {}.".format(dic4) )
dic5 = { x: x**2 for x in range(6) }
print( "The dic5 is {}.".format(dic5) )

#-----------------------------------------------------------------#

L = [ 1,2,3 ]
L = [ x+10 for x in L ]
print( L )
''' equals to '''
L = [1,2,3]
for x in range(len(L)):
	L[x]+=10
print( L )


#----------------------------------------------------------------#
L = [ x+y for x in "ABC" for y in "abc"]
print( L )

#----------------------------------------------------------------#
L = [ lines for lines in open("script1.txt") ] 
print(L)

#----------------------------------------------------------------#
L = list( map( str.upper, open("script1.txt") ) )
print( L )

#-----------------------------------------------------------------#
L = list(range(10))
L1 = [range(10)]
print( L,"v.s." ,L1 )



