#!/usr/bin/python3

# tuple objects is immutable like string and sequence like list and string.
# Tuple object is immutable, like stringe, usaully represent a fixed collection of items.
# A sequence of any type of data called by index, like list.
# Use parantheness to store value.

# Tuples are not like list and dict, which cannot shrink and growth. But can be nested andsupport any data types.
t1 = ( 1, 2, "ABC", ["name", "age"] )
print(t1)
print( "{}".format( t1[3][1] ) )

# Parenthess can be ommited
t2 = 1, 2, "Spam", [ 'A', 'B']
print("The tuple declartion without parenthess is legal: {}".format(t2) )

