#!/usr/bin/python3.5

# No switch statement in Python.
# Alternaltively, useing another way to replace switch

# Method I
# Use If statement


# Method II: Dict-based
choice = "John"
dict1 = {"Eason":123,
		 "John":112,
		 "Merry":144 }

print( {"Eason":123,
		"John":112,
		"Merry":144} [choice] )

print( dict1.get(choice,"No Value" ) )


# Method III: Try statement
try:
	print(dict1["ABC"])
except KeyError: # What is KeyError??
	print( "No value" )

#---------------------------------------------------------------------------------#
# If/Else Ternary Expression
x = 100
if x:
	y = 100
else:
	y = 200
print(y)
''' equals to '''
# Method I
y = 100 if x else 200
print(y)

print( "ABC" ) if  y < 1000 else print( "Nothing!" )
# Like C, printf( "%s\n",( y > 1000 )? "ABC":"Nothing!" );

# Method II
y = ["Nothing",100][bool("")]
print( y )

#----------------------------------------------------------------------------------#



