#!/usr/bin/python3.5

# Forms of assingments 

# Case I
x = "abc"
print( x )

# Case II
x,y="as","sa" # Tuple assignments
print( x, y )
[x1,y1] = [100,200] # List assignments
print( x1, y1 )

# Case III: right of = must be iterable.
a,b,c,d = "ABCD" # **Names are assigned by position.
print( a, " ", b, " ", c," ", d )

A,B,C = [1,2,3] # **Names are assigned by position.
print( A," " ,B," ", C )

# Case IV
h=w="XYZ"
print( h, " ", w, " " )

# Case V: Extended sequence unpacking
p,*k = 'ABE' # p is assigned by A, *k is assigned by the rest of objects in LIST form.
print( "a is %s, *k is %s." %(a,k) )

# Case VI


