#!/usr/bin/python3.5

# Question_line_802

def length( str1, str2 ):
	if len(str1) > len(str2):
		print(str1)
	elif len(str1) < len(str2):
		print(str2)
	else:
		print(str1, str2)

lines = input( "Input two string>> " ).split()

length(lines[0],lines[1])
	


