#!/usr/bin/python3.5

# Question_line_1108 

def YesOrNot( string ):
	if string =="YES" or string =="yes" or string == "Yes":
		print("Yes.")
	else:
		print("No")


str1 = input( ">> " )
YesOrNot(str1)
