#!/usr/bin/python3.5

# Question_line_830

def EvenOrNot( num ):
	if num%2 == 0:
		print( "%s.\n" %("It is an even number") )
	else:
		print( "%s.\n" %("It is an odd number") )


x = int( input("Input an number>> ") )

EvenOrNot( x )

