#!/usr/bin/python3.5

# Question_line_900

def printDict():
	Dict = dict()
	for i in range(1,21):
		Dict[i]=i**2
	Key = Dict.keys()
	''' Solution I
	for key in Key:
		print( "{}".format( Dict[key] ), end=" " )
	'''

	''' Solution II '''
	for ( key, val ) in Dict.items():
		print( val, end = " " )


printDict()
