#!/usr/bin/python3.5

# Question_line_1268

import numpy as np

class Circle():

	def __init__( self, radius ):
		self.radius = radius

	def area( self ):
		return self.radius**2*np.pi


r = int( input(">> Input a radius: ") )

print( Circle(r).area() )
		
